# 
FROM python:3.11.7

# 
WORKDIR /code

# 
COPY ./requirements.txt /code/requirements.txt

# 
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

# 
COPY ./app /code/app

#
ENV OPENAI_API_KEY=
ENV PINECONE_API_KEY=
ENV PINECONE_INDEX_NAME=

# 
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80"]